services:
  frontend:
    environment:
      - REACT_APP_API_URL=/api
      - REACT_APP_OAUTH_ISSUER=http://auth.localhost/dex
      - REACT_APP_OAUTH_CLIENT_ID=chat-app-dev
    ports: []

  backend:
    environment:
      - FLASK_APP=wsgi.py
      - FLASK_ENV=development
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/webapp
      - OAUTH_ISSUER=http://auth.localhost/dex
      - OAUTH_CLIENT_ID=chat-app-dev
      - OAUTH_CLIENT_SECRET=chat-app-dev-secret-12345
      - OAUTH_REDIRECT_URI=http://auth.localhost/auth/callback
      - PUBLIC_OAUTH_ISSUER=http://auth.localhost/dex
    ports: []

  oauth-server:
    # Remove port exposure for proxy mode - only accessible through nginx
    ports: []
    volumes:
      - ./auth-config/dex-config.proxy.yml:/etc/dex/config.proxy.yaml:ro
    command: ["dex", "serve", "/etc/dex/config.proxy.yaml"]

  db:
    ports: [] 