services:
  # Backend service for Live API testing
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - ./backend:/app
      # Mount service account key (NEW WORKING KEY)
      - ./.secrets/gcp/generative-fashion-355408-new-key.json:/app/gcp-key.json:ro
      # Mount test files
      - ./test_modern_gemini_live.py:/app/test_modern_gemini_live.py:ro
      - ./test_live_text_communication.py:/app/test_live_text_communication.py:ro
      - ./test_basic_auth.py:/app/test_basic_auth.py:ro
      - ./test_comprehensive_live_api.py:/app/test_comprehensive_live_api.py:ro
      - ./test_vertex_ai_live_alternatives.py:/app/test_vertex_ai_live_alternatives.py:ro
      - ./test_google_ai_studio_live_api.py:/app/test_google_ai_studio_live_api.py:ro
      - ./test_google_ai_studio_text_demo.py:/app/test_google_ai_studio_text_demo.py:ro
      - ./test_live_connection.py:/app/test_live_connection.py:ro
      - ./test_results:/app/test_results
    environment:
      # Vertex AI Authentication (existing)
      - GOOGLE_APPLICATION_CREDENTIALS=/app/gcp-key.json
      - GOOGLE_CLOUD_PROJECT=generative-fashion-355408
      - GOOGLE_CLOUD_LOCATION=us-central1
      # Google AI Studio Authentication (new for Live API)
      - GEMINI_API_KEY=AIzaSyAof56iear1iUvaJB-3UhRZtHy2ehT3c8U
      # Application settings
      - PYTHONUNBUFFERED=1
      - DEBUG=false
    working_dir: /app
    
  # Standalone test service (no dependencies)
  test:
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - ./backend:/app
      # Mount service account key (NEW WORKING KEY)
      - ./.secrets/gcp/generative-fashion-355408-new-key.json:/app/gcp-key.json:ro
      # Mount test files
      - ./test_modern_gemini_live.py:/app/test_modern_gemini_live.py:ro
      - ./test_live_text_communication.py:/app/test_live_text_communication.py:ro
      - ./test_basic_auth.py:/app/test_basic_auth.py:ro
      - ./test_comprehensive_live_api.py:/app/test_comprehensive_live_api.py:ro
      - ./test_vertex_ai_live_alternatives.py:/app/test_vertex_ai_live_alternatives.py:ro
      - ./test_google_ai_studio_live_api.py:/app/test_google_ai_studio_live_api.py:ro
      - ./test_google_ai_studio_text_demo.py:/app/test_google_ai_studio_text_demo.py:ro
      - ./test_live_connection.py:/app/test_live_connection.py:ro
      - ./test_results:/app/test_results
    environment:
      # Vertex AI Authentication (existing)
      - GOOGLE_APPLICATION_CREDENTIALS=/app/gcp-key.json
      - GOOGLE_CLOUD_PROJECT=generative-fashion-355408
      - GOOGLE_CLOUD_LOCATION=us-central1
      # Google AI Studio Authentication (new for Live API)
      - GEMINI_API_KEY=AIzaSyAof56iear1iUvaJB-3UhRZtHy2ehT3c8U
      # Application settings
      - PYTHONUNBUFFERED=1
    working_dir: /app
    command: python test_comprehensive_live_api.py 