version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - REACT_APP_API_URL=http://localhost:5001/api
      - REACT_APP_WEBSOCKET_URL=ws://localhost:8080
    depends_on:
      backend:
        condition: service_started
      websocket_proxy:
        condition: service_started

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5001:5000"
    volumes:
      - ./backend:/app
      # Updated to use new working service account key
      - ./.secrets/gcp/generative-fashion-355408-new-key.json:/app/gcp-key.json:ro
    env_file:
      - .env  # Load environment variables from .env file (including GEMINI_API_KEY)
    environment:
      - FLASK_APP=wsgi.py
      - FLASK_ENV=development
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/webapp
      # GCS configuration
      - GCS_BUCKET_NAME=cursor-test-llm-assets
      # Service account key for authentication
      - GOOGLE_APPLICATION_CREDENTIALS=/app/gcp-key.json
      # Vertex AI settings
      - GOOGLE_CLOUD_PROJECT=generative-fashion-355408
      - GOOGLE_CLOUD_LOCATION=us-central1
      - GOOGLE_GENAI_USE_VERTEXAI=True
    depends_on:
      db:
        condition: service_healthy
    command: >
      sh -c '
        echo "Database is healthy. Applying database migrations..." &&
        flask db upgrade &&
        echo "Starting Gunicorn..." &&
        gunicorn -k eventlet --bind 0.0.0.0:5000 wsgi:app
      '

  websocket_proxy:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./backend:/app
      # Updated to use new working service account key
      - ./.secrets/gcp/generative-fashion-355408-new-key.json:/app/gcp-key.json:ro
    env_file:
      - .env  # Load environment variables from .env file (including GEMINI_API_KEY)
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=/app/gcp-key.json
      - GOOGLE_CLOUD_PROJECT=generative-fashion-355408
      - GOOGLE_CLOUD_LOCATION=us-central1
      - DEBUG=true
    command: python run_live_proxy.py
    depends_on:
      - backend

  db:
    image: postgres:15
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=webapp
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d webapp || exit 1"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s

volumes:
  postgres_data: 