# Path: backend/migrations/script.py.mako
# This is the Mako template for migration scripts.
# It is used by Alembic to generate new migration files.
"""Add authentication system with User and OAuthAccount models

Revision ID: 0cedea11d655
Revises: '7b9c9b0fb3a3'
Create Date: 2025-06-02 08:06:27.164952

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0cedea11d655'
down_revision = '7b9c9b0fb3a3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=True),
    sa.Column('display_name', sa.String(length=100), nullable=True),
    sa.Column('avatar_url', sa.String(length=500), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('last_login_at', sa.DateTime(), nullable=True),
    sa.Column('timezone', sa.String(length=50), nullable=True),
    sa.Column('language', sa.String(length=10), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)
    op.create_table('o_auth_account',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('provider_id', sa.String(length=100), nullable=False),
    sa.Column('provider_email', sa.String(length=120), nullable=True),
    sa.Column('provider_username', sa.String(length=100), nullable=True),
    sa.Column('access_token', sa.Text(), nullable=True),
    sa.Column('refresh_token', sa.Text(), nullable=True),
    sa.Column('token_expires_at', sa.DateTime(), nullable=True),
    sa.Column('provider_data', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('last_used_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider', 'provider_id', name='unique_provider_account')
    )
    op.create_index(op.f('ix_o_auth_account_provider'), 'o_auth_account', ['provider'], unique=False)
    op.add_column('chat_session', sa.Column('user_id', sa.Integer(), nullable=False))
    op.create_index(op.f('ix_chat_session_user_id'), 'chat_session', ['user_id'], unique=False)
    op.create_foreign_key(None, 'chat_session', 'user', ['user_id'], ['id'])
    op.add_column('interaction_log', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_interaction_log_user_id'), 'interaction_log', ['user_id'], unique=False)
    op.create_foreign_key(None, 'interaction_log', 'user', ['user_id'], ['id'])
    op.add_column('interaction_session_summary', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_interaction_session_summary_user_id'), 'interaction_session_summary', ['user_id'], unique=False)
    op.create_foreign_key(None, 'interaction_session_summary', 'user', ['user_id'], ['id'])
    op.add_column('task', sa.Column('user_id', sa.Integer(), nullable=False))
    op.create_index(op.f('ix_task_user_id'), 'task', ['user_id'], unique=False)
    op.create_foreign_key(None, 'task', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'task', type_='foreignkey')
    op.drop_index(op.f('ix_task_user_id'), table_name='task')
    op.drop_column('task', 'user_id')
    op.drop_constraint(None, 'interaction_session_summary', type_='foreignkey')
    op.drop_index(op.f('ix_interaction_session_summary_user_id'), table_name='interaction_session_summary')
    op.drop_column('interaction_session_summary', 'user_id')
    op.drop_constraint(None, 'interaction_log', type_='foreignkey')
    op.drop_index(op.f('ix_interaction_log_user_id'), table_name='interaction_log')
    op.drop_column('interaction_log', 'user_id')
    op.drop_constraint(None, 'chat_session', type_='foreignkey')
    op.drop_index(op.f('ix_chat_session_user_id'), table_name='chat_session')
    op.drop_column('chat_session', 'user_id')
    op.drop_index(op.f('ix_o_auth_account_provider'), table_name='o_auth_account')
    op.drop_table('o_auth_account')
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    # ### end Alembic commands ### 