# Path: backend/migrations/script.py.mako
# This is the Mako template for migration scripts.
# It is used by Alembic to generate new migration files.
"""Re-add OAuth token fields

Revision ID: 22c8dbaf0064
Revises: 'b23a7260dcda'
Create Date: 2025-06-02 13:15:33.098156

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '22c8dbaf0064'
down_revision = 'b23a7260dcda'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('o_auth_account', sa.Column('access_token', sa.Text(), nullable=True))
    op.add_column('o_auth_account', sa.Column('refresh_token', sa.Text(), nullable=True))
    op.add_column('o_auth_account', sa.Column('token_expires_at', sa.DateTime(), nullable=True))
    op.add_column('user', sa.Column('timezone', sa.String(length=50), nullable=True))
    op.add_column('user', sa.Column('language', sa.String(length=10), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'language')
    op.drop_column('user', 'timezone')
    op.drop_column('o_auth_account', 'token_expires_at')
    op.drop_column('o_auth_account', 'refresh_token')
    op.drop_column('o_auth_account', 'access_token')
    # ### end Alembic commands ### 