# Path: backend/migrations/script.py.mako
# This is the Mako template for migration scripts.
# It is used by Alembic to generate new migration files.
"""add provider field to chat_session

Revision ID: 5a451cc7d4a4
Revises: '06b6b2c2ee44'
Create Date: 2025-05-20 21:31:59.369352

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5a451cc7d4a4'
down_revision = '06b6b2c2ee44'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat_session', sa.Column('provider', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chat_session', 'provider')
    # ### end Alembic commands ### 