# Path: backend/migrations/script.py.mako
# This is the Mako template for migration scripts.
# It is used by Alembic to generate new migration files.
"""Add interaction logging tables

Revision ID: 7b9c9b0fb3a3
Revises: '5a451cc7d4a4'
Create Date: 2025-05-30 01:28:37.484474

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7b9c9b0fb3a3'
down_revision = '5a451cc7d4a4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('interaction_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.String(length=100), nullable=False),
    sa.Column('chat_session_id', sa.Integer(), nullable=True),
    sa.Column('interaction_type', sa.String(length=50), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('user_agent', sa.String(length=500), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.ForeignKeyConstraint(['chat_session_id'], ['chat_session.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_interaction_log_interaction_type'), 'interaction_log', ['interaction_type'], unique=False)
    op.create_index(op.f('ix_interaction_log_session_id'), 'interaction_log', ['session_id'], unique=False)
    op.create_index(op.f('ix_interaction_log_timestamp'), 'interaction_log', ['timestamp'], unique=False)
    op.create_table('interaction_session_summary',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.String(length=100), nullable=False),
    sa.Column('chat_session_id', sa.Integer(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('ended_at', sa.DateTime(), nullable=True),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.Column('total_interactions', sa.Integer(), nullable=True),
    sa.Column('video_frames_sent', sa.Integer(), nullable=True),
    sa.Column('audio_chunks_sent', sa.Integer(), nullable=True),
    sa.Column('text_messages_sent', sa.Integer(), nullable=True),
    sa.Column('api_responses_received', sa.Integer(), nullable=True),
    sa.Column('average_video_frame_rate', sa.Float(), nullable=True),
    sa.Column('total_data_sent_bytes', sa.BigInteger(), nullable=True),
    sa.Column('average_api_response_time_ms', sa.Float(), nullable=True),
    sa.Column('total_errors', sa.Integer(), nullable=True),
    sa.Column('last_error_timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['chat_session_id'], ['chat_session.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_interaction_session_summary_session_id'), 'interaction_session_summary', ['session_id'], unique=True)
    op.create_table('interaction_media_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('interaction_log_id', sa.Integer(), nullable=False),
    sa.Column('storage_type', sa.String(length=50), nullable=False),
    sa.Column('data_inline', sa.LargeBinary(), nullable=True),
    sa.Column('file_path', sa.String(length=500), nullable=True),
    sa.Column('cloud_storage_url', sa.String(length=1000), nullable=True),
    sa.Column('data_hash', sa.String(length=128), nullable=True),
    sa.Column('is_anonymized', sa.Boolean(), nullable=True),
    sa.Column('retention_until', sa.DateTime(), nullable=True),
    sa.Column('is_encrypted', sa.Boolean(), nullable=True),
    sa.Column('encryption_key_id', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['interaction_log_id'], ['interaction_log.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('interaction_metadata',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('interaction_log_id', sa.Integer(), nullable=False),
    sa.Column('frame_rate', sa.Float(), nullable=True),
    sa.Column('audio_sample_rate', sa.Integer(), nullable=True),
    sa.Column('video_resolution_width', sa.Integer(), nullable=True),
    sa.Column('video_resolution_height', sa.Integer(), nullable=True),
    sa.Column('audio_format', sa.String(length=50), nullable=True),
    sa.Column('video_format', sa.String(length=50), nullable=True),
    sa.Column('compression_quality', sa.Float(), nullable=True),
    sa.Column('data_size_bytes', sa.BigInteger(), nullable=True),
    sa.Column('processing_time_ms', sa.Integer(), nullable=True),
    sa.Column('api_endpoint', sa.String(length=200), nullable=True),
    sa.Column('api_response_time_ms', sa.Integer(), nullable=True),
    sa.Column('api_status_code', sa.Integer(), nullable=True),
    sa.Column('camera_on', sa.Boolean(), nullable=True),
    sa.Column('microphone_on', sa.Boolean(), nullable=True),
    sa.Column('is_connected', sa.Boolean(), nullable=True),
    sa.Column('custom_metadata', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['interaction_log_id'], ['interaction_log.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('interaction_metadata')
    op.drop_table('interaction_media_data')
    op.drop_index(op.f('ix_interaction_session_summary_session_id'), table_name='interaction_session_summary')
    op.drop_table('interaction_session_summary')
    op.drop_index(op.f('ix_interaction_log_timestamp'), table_name='interaction_log')
    op.drop_index(op.f('ix_interaction_log_session_id'), table_name='interaction_log')
    op.drop_index(op.f('ix_interaction_log_interaction_type'), table_name='interaction_log')
    op.drop_table('interaction_log')
    # ### end Alembic commands ### 