# Path: backend/migrations/script.py.mako
# This is the Mako template for migration scripts.
# It is used by Alembic to generate new migration files.
"""add chat_session and link to chat_message

Revision ID: 92f9e38332c2
Revises: 'e248c51c1e99'
Create Date: 2025-05-20 09:45:30.387417

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '92f9e38332c2'
down_revision = 'e248c51c1e99'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chat_session',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('chat_message', sa.Column('chat_session_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'chat_message', 'chat_session', ['chat_session_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'chat_message', type_='foreignkey')
    op.drop_column('chat_message', 'chat_session_id')
    op.drop_table('chat_session')
    # ### end Alembic commands ### 