# Path: backend/migrations/script.py.mako
# This is the Mako template for migration scripts.
# It is used by Alembic to generate new migration files.
"""Simplify User and OAuthAccount models - remove unnecessary fields

Revision ID: b23a7260dcda
Revises: '0cedea11d655'
Create Date: 2025-06-02 08:22:43.837948

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'b23a7260dcda'
down_revision = '0cedea11d655'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('o_auth_account', 'refresh_token')
    op.drop_column('o_auth_account', 'access_token')
    op.drop_column('o_auth_account', 'token_expires_at')
    op.drop_column('user', 'language')
    op.drop_column('user', 'timezone')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('timezone', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('user', sa.Column('language', sa.VARCHAR(length=10), autoincrement=False, nullable=True))
    op.add_column('o_auth_account', sa.Column('token_expires_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('o_auth_account', sa.Column('access_token', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('o_auth_account', sa.Column('refresh_token', sa.TEXT(), autoincrement=False, nullable=True))
    # ### end Alembic commands ### 