# Path: backend/migrations/script.py.mako
# This is the Mako template for migration scripts.
# It is used by Alembic to generate new migration files.
"""add chat_message table

Revision ID: e248c51c1e99
Revises: 'initial_migration'
Create Date: 2025-05-20 09:42:28.592852

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e248c51c1e99'
down_revision = 'initial_migration'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chat_message',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('sender', sa.String(length=50), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('chat_message')
    # ### end Alembic commands ### 