# Path: backend/migrations/script.py.mako
# This is the Mako template for migration scripts.
# It is used by Alembic to generate new migration files.
"""Add media columns to chat_message table

Revision ID: ead31528e0df
Revises: '92f9e38332c2'
Create Date: 2025-05-20 13:33:08.926673

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ead31528e0df'
down_revision = '92f9e38332c2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat_message', sa.Column('media_type', sa.String(length=50), nullable=True))
    op.add_column('chat_message', sa.Column('media_url', sa.String(length=500), nullable=True))
    op.alter_column('chat_message', 'text',
               existing_type=sa.TEXT(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('chat_message', 'text',
               existing_type=sa.TEXT(),
               nullable=False)
    op.drop_column('chat_message', 'media_url')
    op.drop_column('chat_message', 'media_type')
    # ### end Alembic commands ### 